### ISSUE TITLE
Do you like the TSDX x Next.js workflow?

### ISSUE THREAD

**Issue by jaredpalmer** [tailwindlabs/tailwindui-react#9]
Wondering if this repo setup (with tsdx in src/index and next.js in root) should be an official template. Curious to hear your overall feedback or how this could be improved.

**Comment by RobinMalfait** [comment]
Hey @jaredpalmer, thanks for reaching out!

So far I am liking this approach because it allows me to develop, build, and test the components (tsdx) and also test it in a "real world" environment using Next.js which also helps with testing server side rendering.

There are some issues I had to make it actually work, but those issues are mostly related to Next.js:

- Next.js treats the `pages` directory as this special directory, it would be cool to be able to rename this to `documentation` or `playground` or something. We probably can't change anything here, or at least not from TSDX' standpoint.
- Next.js mutates the `tsconfig.json` file, specifically the `compilerOptions.jsx` is set from `react` to `preserve` https://github.com/tailwindlabs/tailwindui-react/blob/04f62133fdcdd7e4e069d9f94446c5b76482a8eb/tsconfig.json#L21 this means that every time I ran `yarn playground` (`next dev` behind the scenes) the tests & build of tsdx broke. Because of this I had to do numerous of changes:
  1. I introduced a `tsconfig.tsdx.json` which extends the default one, but overrides that `jsx` config from above: https://github.com/tailwindlabs/tailwindui-react/blob/04f62133fdcdd7e4e069d9f94446c5b76482a8eb/tsconfig.tsdx.json#L1-L7
  2. This also means that `jest` doesn't work anymore, to fix that I created a `jest.config.js` file which references the correct (new) `tsconfig.tsdx.json` file: https://github.com/tailwindlabs/tailwindui-react/blob/04f62133fdcdd7e4e069d9f94446c5b76482a8eb/jest.config.js#L6
  3. This also means that the normal "build" doesn't work anymore, so I had to update the script so that it references the correct (new) `tsconfig.tsdx.json` file: https://github.com/tailwindlabs/tailwindui-react/blob/04f62133fdcdd7e4e069d9f94446c5b76482a8eb/package.json#L16

I think a nice solution would be to auto detect `tsconfig.tsdx.json` or something similar so that I don't have to add the `jest.config.json` file and edit the `package.json` script.

---

A final issue I found is that vscode gets confused. It could be that I misconfigured some things to make it actually work, however when running `next dev` it "works" in the browser so I didn't worry about it too much (yet). This also has no impact on the actual "library" so probably nothing to do with `tsdx` itself.

![image](https://user-images.githubusercontent.com/1834413/91747951-6bea0080-ebbf-11ea-831a-c1dce21355d1.png)

**Comment by RobinMalfait** [comment]
Hey! I'm deprecating this repository in favor of the [Headless UI repo](https://github.com/tailwindlabs/headlessui). If this is still an issue please re-open the issue in the new repository. Thank you!
